### ISSUE TITLE
Regression: Doesn't remember the width of the sidebar

### ISSUE THREAD

**Issue by SmaugTheGreat** [Croydon/vertical-tabs-reloaded#129]
Add-on version: 0.8.5
Firefox version: 56.0
OS + OS-Version: Windows 7

Since the last October 1st update, the width of the sidebar always gets set to only show the icons but not the tab titles. I have to manually resize it every time now that I start Firefox. Pretty annoying.

**Comment by Croydon** [comment]
@SmaugTheGreat Please update to v0.8.5.1 and report if this bug is still existing for you :)

**Comment by sabi0** [comment]
Update to 0.8.5.1 fixed restoring the width. But the position (left / right) is still not remembered.
Irregardless of the setting I always have tab bar displayed on the left after restarting Firefox.

**Comment by sabi0** [comment]
Btw, the setting works as a dummy toggle.
Say I have tab bar on the left while "display on the right" is checked. When I uncheck the option (i.e. tabs should be on the left) the tab bar is moved to the right.
I believe it should use the current checked state instead of something like onchange = flipTabBarPosition().

**Comment by sabi0** [comment]
The above tab bar position problem seems to be an artifact of Firefox 55.0.3. Now that I upgraded to Firefox 56.0 the problem is gone.

**Comment by Croydon** [comment]
@sabi0 It still could happened with FF57 with v0.8.5.1. v0.8.5.2 should fix it now for the tab sidebar position as well.

Please provide feedback if this is happening again with v0.8.5.2.

**Comment by SmaugTheGreat** [comment]
The update fixed the problem with the width for me :) Thanks!

**Comment by SmaugTheGreat** [comment]
Nevermind, it's not fully fixed yet. If I adjust the width and then restart the browser, it remembers it. However, if I then don't change the width and restart the browser, it gets set back to minimal width :(

**Comment by Croydon** [comment]
@SmaugTheGreat Are you sure that it is related to setting a new width i.e. can you reproduce it again and again?

From my current understanding this bug comes from a race from Firefox and VTR, whoever sets this attributes the last "wins".

**Comment by SmaugTheGreat** [comment]
Hm, it was reproducable yesterday, however it's not reproducable today :S

**Comment by woj-tek** [comment]
I also had the same issue. It's really hit-or-miss - sometimes when I start Fx the tabbar is on the left (even though I have checked "on the right" [and disabling it moves it to the right -- rather confusing]) and it's very narrow. Looks/feels like some settings access problem.

**Comment by Croydon** [comment]
> and disabling it moves it to the right -- rather confusing

This is fixed.

> I also had the same issue.

You had this problem or do you still have it with v0.8.5.2?

**Comment by woj-tek** [comment]
It seems to be working ok with v0.8.5 **.2**

**Comment by SmaugTheGreat** [comment]
It not remembering the width definitely does still happen occasionally, it's just not reproducible.

**Comment by Croydon** [comment]
I have implemented workarounds for the most cases in v0.8.5.1 and v0.8.5.2.

Since we are two weeks away now from the FF57 release I will definitely not spend time on this anymore, sorry.
