### ISSUE TITLE
New windows don't respect the hide toolbar preference

### ISSUE THREAD

**Issue by darrinhenein** [Croydon/vertical-tabs-reloaded#215]
Add-on version: 0.12.0
Firefox version: 65.0a1
OS + OS-Version: OSX 10.14.1
Other tab + user interface related add-ons: n/a

**Comment by darrinhenein** [comment]
Looks like this could be related to #212 based on the comments there.

**Comment by Croydon** [comment]
Yes, it was fixed after the report in #212 and I just cut a release.
Please update to 0.12.1 and report back if this fixed it for you.

**Comment by darrinhenein** [comment]
Looks good! I still see a flicker of the toolbar before it hides, but that's ignorable ;) Thanks for the quick fix 🙏
